version: '3'

services:
  app:
    build: .
    environment:
      - "RAILS_ENV=development"
      - "VIRTUAL_HOST=test.railstutorial.u6k.me"
      - "VIRTUAL_PORT=3000"
      - "LETSENCRYPT_HOST=test.railstutorial.u6k.me"
      - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
    volumes:
      - ".:/var/myapp"
    ports:
      - "3000:3000"

networks:
  default:
    external:
      name: documents_default

